In [25]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import seaborn as sns

from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from sklearn.model_selection import cross_val_score, cross_val_predict, train_test_split
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import GridSearchCV

In [2]:
ls

Data Clean final.ipynb
Data Cleaning 2.ipynb
Data_Skills-master/
GA-DSI-master/
Job-Salary-Webscraping-and-Prediction-master/
Project 4 - Data Cleaning.ipynb
Project 4 - question 1.ipynb
Project 4 web scrape #2.ipynb
Project_4_web_scrape.ipynb
README.md*
advert.csv
chromedriver/
company1
job_linker1.csv
linkedin-jobs-scraper-master/
rawdata.csv
scrape-indeed-data-jobs-master/
seek.csv
seek_clean.csv
seeker.csv
web scrape #3.ipynb

In [3]:
'''
Here I modelled the high and low salaries on categories excluding job_description.

Start by loading in the cleaned data.
'''

df = pd.read_csv('./seek_clean.csv', index_col = None)

In [4]:
df = df.drop(['Unnamed: 0'], axis = 1)

In [5]:
df.head()

,job_title,job_location,advertiser,url,job_post_date,job_desc,pay_total2,jbd
0,data scientist,Sydney,Motion Recruitment,www.seek.com.au/job/38274601?type=standout&sea...,23 Jan 2019,ABOUT QHR/eQ8 year of providing consulting...,120999.45,Normal Data Scientist
1,data science delivery lead,Sydney,Intellify,www.seek.com.au/job/38267034?type=standout&sea...,5 Feb 2019,About Intellify Intellify is a data science an...,165000.00,Senior Data Scientist
2,head of data science engineering & products,Sydney,FIRESOFT Consulting,www.seek.com.au/job/38248336?type=standard&sea...,1 Feb 2019,Head of Data Science Engineering & Products - ...,120999.45,Normal Data Scientist
3,machine learning engineer / scientist - optimi...,Sydney,Infopeople,www.seek.com.au/job/38178979?type=standard&sea...,23 Jan 2019,This role is a newly created role to work with...,160000.00,Senior Data Scientist
4,data analytics & data science team leader,Sydney,AUSTRALIAN FEDERAL POLICE,www.seek.com.au/job/38194317?type=standout&sea...,25 Jan 2019,The mission of the AFP is to provide dynamic a...,115046.50,Senior Data Scientist

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1803 entries, 0 to 1802
Data columns (total 8 columns):
job_title        1803 non-null object
job_location     1803 non-null object
advertiser       1803 non-null object
url              1803 non-null object
job_post_date    1803 non-null object
job_desc         1803 non-null object
pay_total2       1803 non-null float64
jbd              1803 non-null object
dtypes: float64(1), object(7)
memory usage: 112.8+ KB

In [8]:
df['salary'] = np.nan

In [9]:
med_nbi = 118146.60
med_nda = 121000
med_nde = 125000
med_nds = 120999.45
med_sbi = 125000
med_sda = 150000
med_sde = 135000
med_sds = 140000

In [10]:
'''
I define that a high salary is one that is greater than the median value for the job category. Here I create the 
high or normal salary in a new column called salary.
'''

for index, row in df.iterrows():
    if row['jbd'] == 'Normal Data Scientist' and row['pay_total2'] > med_nds:
        df.salary[index] = 1
    elif row['jbd'] == 'Normal Business Intelligence' and row['pay_total2'] > med_nbi:
        df.salary[index] = 1
    elif row['jbd'] == 'Normal Data Engineer' and row['pay_total2'] > med_nde:
        df.salary[index] = 1
    elif row['jbd'] == 'Normal Data Analyst' and row['pay_total2'] > med_nda:
        df.salary[index] = 1  
    elif row['jbd'] == 'Senior Business Intelligence' and row['pay_total2'] > med_sbi:
        df.salary[index] = 1    
    elif row['jbd'] == 'Senior Data Engineer' and row['pay_total2'] > med_sde:
        df.salary[index] = 1
    elif row['jbd'] == 'Senior Data Analyst' and row['pay_total2'] > med_sda:
        df.salary[index] = 1    
    elif row['jbd'] == 'Senior Data Scientist' and row['pay_total2'] > med_sds:
        df.salary[index] = 1
    else:
        df.salary[index] = 0

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [11]:
'''
Here I determine the baseline by calculating the distribution of high and normal salary.
'''

df.salary.value_counts(normalize=True)

0.0    0.78924
1.0    0.21076
Name: salary, dtype: float64

In [12]:
df

,job_title,job_location,advertiser,url,job_post_date,job_desc,pay_total2,jbd,salary
0,data scientist,Sydney,Motion Recruitment,www.seek.com.au/job/38274601?type=standout&sea...,23 Jan 2019,ABOUT QHR/eQ8 year of providing consulting...,120999.45,Normal Data Scientist,0.0
1,data science delivery lead,Sydney,Intellify,www.seek.com.au/job/38267034?type=standout&sea...,5 Feb 2019,About Intellify Intellify is a data science an...,165000.00,Senior Data Scientist,1.0
2,head of data science engineering & products,Sydney,FIRESOFT Consulting,www.seek.com.au/job/38248336?type=standard&sea...,1 Feb 2019,Head of Data Science Engineering & Products - ...,120999.45,Normal Data Scientist,0.0
3,machine learning engineer / scientist - optimi...,Sydney,Infopeople,www.seek.com.au/job/38178979?type=standard&sea...,23 Jan 2019,This role is a newly created role to work with...,160000.00,Senior Data Scientist,1.0
4,data analytics & data science team leader,Sydney,AUSTRALIAN FEDERAL POLICE,www.seek.com.au/job/38194317?type=standout&sea...,25 Jan 2019,The mission of the AFP is to provide dynamic a...,115046.50,Senior Data Scientist,0.0
5,senior data science executive,Sydney,The Nielsen Company (Australia) Pty Ltd,www.seek.com.au/job/38257609?type=standout&sea...,4 Feb 2019,Nielsen is a global performance management com...,140000.00,Senior Data Scientist,0.0
6,junior data scientist,Sydney,Motion Recruitment,www.seek.com.au/job/38108166?type=standout&sea...,15 Jan 2019,About the business and the role My client is ...,120999.45,Normal Data Scientist,0.0
7,data scientist with consultancy experience,Sydney,360HR Pty Ltd,www.seek.com.au/job/38261034?type=standard&sea...,4 Feb 2019,"In this role, you will be managing data from m...",120999.45,Normal Data Scientist,0.0
8,senior data science (loyalty) :: $170k + super...,Sydney,Correlate Resources,www.seek.com.au/job/38153321?type=standout&sea...,21 Jan 2019,Senior Data Scientist (Loyalty) :: $170K + Sup...,187000.00,Senior Data Scientist,1.0
9,senior data scientist,Sydney,Preacta Recruitment,www.seek.com.au/job/38265180?type=standard&sea...,5 Feb 2019,Currently working for one of Australiaâs leadi...,140000.00,Senior Data Scientist,0.0
10,manager | analytics & data science,Sydney,Bluefin Resources Pty Limited,www.seek.com.au/job/38214944?type=standard&sea...,29 Jan 2019,My client is a leading institution with ongoin...,120999.45,Normal Data Scientist,0.0
11,data scientist,Sydney,Talent â Winner âSeek Large Recruitment Agency...,www.seek.com.au/job/38112245?type=standout&sea...,15 Jan 2019,Data Scientist - Cognitive Science & AIJoin th...,100000.00,Normal Data Scientist,0.0
12,ghd digital - analytics / data science lead - ...,Sydney,GHD Pty Ltd,www.seek.com.au/job/38130368?type=standard&sea...,17 Jan 2019,GHD is one of the world's leading professional...,140000.00,Senior Data Scientist,0.0
13,data scientist,Sydney,QHR,www.seek.com.au/job/38178403?type=standout&sea...,23 Jan 2019,ABOUT QHR/eQ8 year of providing consulting...,120999.45,Normal Data Scientist,0.0
14,data science - research,Sydney,Hudson,www.seek.com.au/job/38059567?type=standout&sea...,9 Jan 2019,Full-time Remuneration package: $110 + super ...,120999.45,Normal Data Scientist,0.0
15,data scientist,Sydney,Precision Sourcing,www.seek.com.au/job/38140287?type=standout&sea...,18 Jan 2019,The CompanyThis is one of the most exciting co...,145000.00,Normal Data Scientist,1.0
16,data scientist,Sydney,Caltex Australia,www.seek.com.au/job/38096678?type=standout&sea...,14 Jan 2019,Deliver insights with predictive analytics an...,120999.45,Normal Data Scientist,0.0
17,data scientist - 1 year ftc role - possibility...,Sydney,Infopeople,www.seek.com.au/job/38093511?type=standard&sea...,14 Jan 2019,I am looking for a Data Scientist with 1-2 yea...,120999.45,Normal Data Scientist,0.0
18,senior business intelligence consultant,Sydney,AI Australia,www.seek.com.au/job/38225977?type=standout&sea...,30 Jan 2019,As a leading Australian owned Artificial Intel...,85000.00,Senior Business Intelligence,0.0
19,"data scientist, analytics, machine learning - ...",Sydney,Infinity Pro,www.seek.com.au/job/38239400?type=standard&sea...,31 Jan 2019,Your Benefits: Great Package; Generous Bonuse...,140000.00,Senior Data Scientist,0.0
20,data scientist,Sydney,The Yield,www.seek.com.au/job/38066139?type=standard&sea...,23 Jan 2019,ABOUT QHR/eQ8 year of providing consulting...,120999.45,Normal Data Scientist,0.0
21,senior pricing data scientist,Sydney,Toyota Financial Services,www.seek.com.au/job/38249571?type=standout&sea...,1 Feb 2019,Toyota Financial Services is the country's lar...,140000.00,Senior Data Scientist,0.0
22,senior big data engineer - successful data sci...,Sydney,Talent Insights Group Pty Ltd,www.seek.com.au/job/38129848?type=standout&sea...,17 Jan 2019,Full Job Description We are currently recrui...,140000.00,Senior Data Scientist,0.0
23,ghd digital - asset data scientist â canberra,Sydney,GHD Pty Ltd,www.seek.com.au/job/38084908?type=standard&sea...,11 Jan 2019,About GHD: Â GHD is one of the world's leading...,120999.45,Normal Data Scientist,0.0
24,senior data scientist,Sydney,News Corp Australia,www.seek.com.au/job/38100171?type=standout&sea...,14 Jan 2019,The role will be focused on stitching together...,140000.00,Senior Data Scientist,0.0
25,research scientist - blockchain and software ...,Sydney,CSIRO,www.seek.com.au/job/38200815?type=standout&sea...,25 Jan 2019,Apply your expertise in computer science/soft...,184250.00,Normal Data Scientist,1.0
26,"consultant - data, analytics and machine learn...",Sydney,Alloc8,www.seek.com.au/job/38094512?type=standout&sea...,14 Jan 2019,We're proud to call this company a client and ...,150000.00,Senior Data Analyst,0.0
27,senior data scientist,Sydney,QBE,www.seek.com.au/job/38070249?type=standard&sea...,14 Jan 2019,The role will be focused on stitching together...,140000.00,Senior Data Scientist,0.0
28,data scientist - global company - solve futuri...,Sydney,TRS - IT & Communications,www.seek.com.au/job/38096732?type=standard&sea...,14 Jan 2019,Outstanding opportunity to join a global compa...,120999.45,Normal Data Scientist,0.0
29,senior data engineer,Sydney,Drive Yello,www.seek.com.au/job/38091794?type=standout&sea...,14 Jan 2019,Welcome to Drive Yello! Weâre a last-mile deli...,135000.00,Senior Data Engineer,0.0
...,...,...,...,...,...,...,...,...,...
1773,principal engineer - rail signalling,Sydney,Arcadis Australia Pacific,www.seek.com.au/job/38110461?type=standard&sea...,15 Jan 2019,Opportunity to work with global consultancy f...,125000.00,Normal Data Engineer,0.0
1774,devops engineer,Sydney,2XM Technology Pty Ltd,www.seek.com.au/job/38075513?type=standard&sea...,31 Jan 2019,Role TitleDevOps Engineer â Institutional - Sy...,125000.00,Normal Data Engineer,0.0
1775,automation engineer,Sydney,2XM Technology Pty Ltd,www.seek.com.au/job/38080179?type=standard&sea...,11 Jan 2019,The CompanyGlobally and award winning Saas pla...,125000.00,Normal Data Engineer,0.0
1776,combat systems engineer,Sydney,NAVANTIA AUSTRALIA PTY LTD,www.seek.com.au/job/38076143?type=standout&sea...,11 Jan 2019,About Us: Navantia Australia specialises in pr...,125000.00,Normal Data Engineer,0.0
1777,technical product engineer,Sydney,Nicriel Partners Pty Ltd,www.seek.com.au/job/38171072?type=standard&sea...,22 Jan 2019,With manufacturing facilities in Australia and...,125000.00,Normal Data Engineer,0.0
1778,devops engineer,Sydney,BHAG MANAGEMENT PTY LTD,www.seek.com.au/job/38075773?type=standout&sea...,31 Jan 2019,Role TitleDevOps Engineer â Institutional - Sy...,125000.00,Normal Data Engineer,0.0
1779,"java software engineer (full stack) - java, sp...",Sydney,Amplify Partners Pty Ltd,www.seek.com.au/job/38098672?type=standard&sea...,14 Jan 2019,Full Stack Java Engineers - PermanentÂ We're...,132000.00,Normal Data Engineer,1.0
1780,javascript engineer - blockchain,Sydney,Robert Walters,www.seek.com.au/job/38069096?type=standard&sea...,10 Jan 2019,You will be building components and applicatio...,125000.00,Normal Data Engineer,0.0
1781,cyber detection engineer,Sydney,Commonwealth Bank - Enterprise Services,www.seek.com.au/job/38041409?type=standout&sea...,8 Jan 2019,Do work that matters\nEnterprise Services (ES)...,125000.00,Normal Data Engineer,0.0
1782,devops engineer,Sydney,Hudson,www.seek.com.au/job/38064128?type=standout&sea...,10 Jan 2019,"Our Client, a Global organization is seeking t...",273750.00,Normal Data Engineer,1.0
1783,central region engineer (electrical),Sydney,Vinidex Pty Limited,www.seek.com.au/job/38121705?type=standout&sea...,16 Jan 2019,"Established since 1960, Vinidex is at the fore...",125000.00,Normal Data Engineer,0.0
1784,lead electrical engineer / asp level 3 & road ...,Sydney,Arcadis Australia Pacific,www.seek.com.au/job/37937636?type=standard&sea...,11 Jan 2019,Experience working in multi discipline design...,135000.00,Senior Data Engineer,0.0
1785,senior manager - security engineering,Sydney,Woolworths Group,www.seek.com.au/job/38206532?type=standard&sea...,28 Jan 2019,Senior Manager - Security Engineering Norwe...,135000.00,Senior Data Engineer,0.0
1786,cloud support engineer - level 2,Sydney,TPG Telecom Limited,www.seek.com.au/job/38056876?type=standout&sea...,9 Jan 2019,About the Company\nTPG is driven by the belief...,125000.00,Normal Data Engineer,0.0
1787,4 x front end angular engineers,Sydney,SustainAbility Consulting,www.seek.com.au/job/38203027?type=standout&sea...,25 Jan 2019,The companyWe are a global technology company ...,530000.00,Normal Data Engineer,1.0
1788,"full stack software engineer (javascript, node...",Sydney,Terem Technologies,www.seek.com.au/job/38056865?type=standard&sea...,9 Jan 2019,Weâre one of Australiaâs fastest growing compa...,125000.00,Normal Data Engineer,0.0
1789,efficiency project engineer / specialist,Sydney,Air Liquide,www.seek.com.au/job/38107353?type=standard&sea...,15 Jan 2019,Air Liquide is the world leader in gases for i...,125000.00,Normal Data Engineer,0.0
1790,telecommunication field engineers,Sydney,Cita Services Pty Ltd,www.seek.com.au/job/38253013?type=standout&sea...,2 Feb 2019,CITA Services provides high quality telecommun...,80300.00,Normal Data Engineer,0.0
1791,surveyor - building & civil engineering,Sydney,Framework Search & Select Pty Ltd,www.seek.com.au/job/38088196?type=standard&sea...,13 Jan 2019,SurveyorsÂ - Building & Civil EngineeringÂ Â Â ...,135000.00,Normal Data Engineer,1.0
1792,"software engineers x3 (python,c++ etc.) produc...",Sydney,inDmand Career Solutions,www.seek.com.au/job/38091701?type=standard&sea...,14 Jan 2019,I am currently recruiting for one of the most ...,125000.00,Normal Data Engineer,0.0
1793,mechanical project engineer,Sydney,Cononbrig Partners,www.seek.com.au/job/38153469?type=standout&sea...,21 Jan 2019,About the business and the role Diverse rang...,112500.00,Normal Data Engineer,0.0
1794,marketing coordinator - norman disney & young ...,Sydney,Norman Disney & Young,www.seek.com.au/job/38053250?type=standard&sea...,9 Jan 2019,Role Purpose & Key Accountabilities The Market...,125000.00,Normal Data Engineer,0.0
1795,business improvement specialist,Sydney,AUSGRID,www.seek.com.au/job/38242525?type=standard&sea...,1 Feb 2019,About Ausgrid\nAusgrid is an energy services b...,118146.60,Normal Business Intelligence,0.0
1796,junior carrier business sales,Sydney,China Telecom (Australia) Pty Ltd,www.seek.com.au/job/38198018?type=standout&sea...,25 Jan 2019,Junior Carrier Business Sales https://youtu.be...,118146.60,Normal Business Intelligence,0.0
1797,sales professional/ business acquisition,Sydney,Black Lab Design Pty Ltd,www.seek.com.au/job/38054868?type=standout&sea...,9 Jan 2019,Sales Engineer/ Business Acquisition Â Would ...,118146.60,Normal Business Intelligence,0.0
1798,finance business partner - defence,Sydney,Serco Asia Pacific,www.seek.com.au/job/38179163?type=standout&sea...,23 Jan 2019,Join the finance team in the Defence portfolio...,118146.60,Normal Business Intelligence,0.0
1799,associate practice engagement manager,Sydney,Infosys limited,www.seek.com.au/job/38225212?type=standard&sea...,30 Jan 2019,Infosys â Global Markets The Global Markets te...,179999.50,Normal Data Engineer,1.0
1800,business development manager - lighting,Sydney,Gerard Lighting Group,www.seek.com.au/job/38177573?type=standout&sea...,23 Jan 2019,Promote a reputable brand that is well known w...,118146.60,Normal Business Intelligence,0.0
1801,surveyor - multi disciplined survey company,Sydney,Framework Search & Select Pty Ltd,www.seek.com.au/job/38134321?type=standard&sea...,17 Jan 2019,Surveyor â Multi Disciplined Survey CompanyÂ Â Â ...,135000.00,Normal Data Scientist,1.0
1802,business development manager industrial refrig...,Sydney,Unknown,www.seek.com.au/job/38105417?type=standard&sea...,15 Jan 2019,"About the business and the role EVAPCO, Inc. ...",118146.60,Normal Business Intelligence,0.0

In [24]:
'''
I have saved a csv of this modified cleaned dataset for more modelling in another jupyter notebook.
'''

df.to_csv('./df_modelling')

In [13]:
'''
Here set X (and dummy it), y, train and test split it.
'''

X = df[['advertiser','job_post_date', 'jbd']].copy()

In [14]:
X = pd.get_dummies(X, drop_first=True, dtype=float)

In [15]:
y = df['salary']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [17]:
'''
Model it with Logistic Regression.
'''

model = LogisticRegression()
model.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
y_pred = model.predict(X_test)
y_score = model.decision_function(X_test)

In [20]:
'''
Gridsearch to optimise hyperparameters.
'''
logreg = LogisticRegression(solver='liblinear')
C_vals = [0.0001, 0.001, 0.01, 0.1, .15, .25, .275, .33, 0.5, .66, 0.75, 1.0, 2.5, 5.0, 10.0, 100.0, 1000.0]
penalties = ['l1','l2']

gs = GridSearchCV(logreg, {'penalty': penalties, 'C': C_vals}, verbose=False, cv=3)
gs.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'penalty': ['l1', 'l2'], 'C': [0.0001, 0.001, 0.01, 0.1, 0.15, 0.25, 0.275, 0.33, 0.5, 0.66, 0.75, 1.0, 2.5, 5.0, 10.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=False)

In [21]:
'''
Check best params and estimator
'''

gs.best_params_

{'C': 5.0, 'penalty': 'l2'}

In [22]:
gs.best_estimator_

LogisticRegression(C=5.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
'''
Create confusion matrix do see where model is predicting false positives and negatives.
'''

conmat = np.array(confusion_matrix(y_test, y_pred, labels=[1,0]))
confusion = pd.DataFrame(conmat, index=['high_salary', 'low_salary'],
                         columns=['predict_highsalary','predict_lowsalary'])

print(confusion)

roc_auc_score(y_test, y_score)

             predict_highsalary  predict_lowsalary
high_salary                  21                 82
low_salary                   10                428

0.7898213414904465